version: '3'
# This environment can be run locally and used for development
services:
  postgres:
    image: postgres:alpine
     # Make Postgres log to a file.
     # More on logging with Postgres: https://www.postgresql.org/docs/current/static/runtime-config-logging.html
    environment:
      POSTGRES_USER: "damien"
      POSTGRES_PASSWORD : "password"
      POSTGRES_DB : "postgres" ## Not really needed as we'll create our own... however. If this is ommitted, one based on POSTGRES_USER will be created.. which we don't wnat
    # The default logs are written to /var/lib/postgresql/data/pg_log#. I think that you can use -c log_directory=/logs to send to a different localtion (assuming it exists)
    command: postgres -c logging_collector=on -c log_destination=stderr -c log_statement=all
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../code_and_data:/code_and_data
    restart: unless-stopped 
volumes:
  pgdata:
  
